INSERT INTO livre (titre,auteur,editeur,date_de_creation,langue,resume,isbn,categorie_id,illustration_id)
VALUES
	('Schtroumpf les bains','Thierry Culliford','Le Lombard','2019-06-05','Français','Après 51 ans de bons et loyaux services, le Schtroumpf Bricoleur commence à en avoir plein le schtroumpf d''être le schtroumpf à tout faire du village ! Et le voilà qui part se reschtroumpfer quelques jours au bord du lac. Jamais inactif, il en profite pour se construire une petite maison. Mais, son idée fait des émules et, bien vite, le havre de paix devient un village de vacances très (et bien trop) à la mode ! L''explosion du tourisme de masse revue et schtroumpfée par les petits lutins de Peyo, avec humour et justesse, comme toujours ! ','978-2803676644',1,1),
	('Marsupilami c''est quoi ce cirque','Franquin Batem & Dugomier','Marsu Productions','2019-06-05','Français','Le Marsupilami et son ami Loucas forment un duo de choc sous le chapiteau du cirque Zabaglione. Même le dompteur Noé ne parvient pas à freiner leurs folies insolites. Un véritable bestiaire forain et des tours de magie à gogo : le cirque Zabaglione a plus d''un tour dans son sac ! ','979-1034742295',1,2),
	('Dans la combi de Thomas Pesquet','Marion Montaigne','DARGAUD','2017-09-24','Français','Le 2 juin dernier, le Français Thomas Pesquet, 38 ans, astronaute, rentrait sur Terre après avoir passé 6 mois dans la Station spatiale internationale. La réalisation d''un rêve d''enfant pour ce type hors-norme qui après avoir été sélectionné parmi 8413 candidats, suivit une formation intense pendant 7 ans, entre Cologne, Moscou, Houston et Baïkonour Dans cette bande dessinée de reportage, Marion Montaigne raconte avec humour sa marque de fabrique le parcours de ce héros depuis sa sélection, puis sa formation jusqu''à sa mission dans l''ISS et son retour sur Terre. ','978-2205076394',2,3),
	('L''étranger','Albert Camus','Gallimard','1971-12-05','Français','«Quand la sonnerie a encore retenti, que la porte du box s''est ouverte, c''est le silence de la salle qui est monté vers moi, le silence, et cette singulière sensation que j''ai eue lorsque j''ai constaté que le jeune journaliste avait détourné les yeux. Je n''ai pas regardé du côté de Marie. Je n''en ai pas eu le temps parce que le président m''a dit dans une forme bizarre que j''aurais la tête tranchée sur une place publique au nom du peuple français...» ','978-2070360024',3,4),
	('La Fontaine : Fables','Jean-Charles Darmon','Le Livre de Poche','2002-06-12','Français','Les Fables occupent une place singulière dans notre mémoire : par le souvenir que nous gardons de ces poèmes devant lesquels nous sommes restés enfants, mais aussi par la grâce de tant de vers devenus proverbiaux  et que notre parole quotidienne fait renaître. Et tout  se passe comme si une correspondance secrète se maintenait de siècle en siècle entre ces Fables et l''identité de notre pays comme de notre langue. Le premier recueil paraît en 1668, et le second dix ans plus tard. Le succès est immense et les poèmes, alors, appartiennent pleinement à leur temps : la France du règne de Louis XIV. Mais le mystère de leur pouvoir est de s''émanciper très vite de cet environnement immédiat, d''éclairer nos réalités successives, d''allier de manière toujours éclatante le particulier et l''universel. Dans cette «comédie à cent actes divers, / Et dont la scène est  l''Univers», le texte se dérobe à toute signification définitive. Mais La Fontaine, à chaque page, nous convainc que la poésie, à ses yeux, demeure instrument de connaissance : il existe une beauté du savoir - et nous ne cessons pas de la retrouver en lui.', '978-2253010043',3,5),
	('LUCA','Franck THILLIEZ','Fleuve éditions','2019-05-02','Français','Partout, il y a la terreur.Celle d''une jeune femme dans une chambre d''hôtel sordide, ventre loué à prix d''or pour couple en mal d''enfant, et qui s''évapore comme elle était arrivée. Partout, il y a la terreur.','978-2265117815',4,6),
	('Pensées pour moi-même','Marc Aurèle','Flammarion','1999-01-04','Français','On sent en soi-même un plaisir secret lorsqu''on parle de cet empereur ; on ne peut lire sa vie sans une espèce d''attendrissement ; tel est l''effet qu''elle produit qu''on a meilleure opinion de soi-même, parce qu''on a meilleure opinion des hommes. ','978-2080700162',5,7),
	('La cuisinière','Mary Beth KEANE','10 X 18','2016-03-17','Français','Immigrée irlandaise courageuse et obstinée arrivée seule à New York à la fin du XIXe siècle, Mary Mallon travaille comme lingère avant de se découvrir un talent caché pour la cuisine. Malheureusement, dans toutes les maisons bourgeoises où elle est employée, les gens contractent la typhoïde, et certains en meurent. Mary, de son côté, ne présente aucun symptôme de la maladie. Au contraire, sa robustesse est presque indécente. Des médecins finissent par s''intéresser à son cas, mais la cuisinière déteste qu''on l''observe comme une bête curieuse et refuse de coopérer. Pourquoi la traite-t-on comme une malade alors qu''elle est en parfaite santé ? Les autorités sanitaires, qui la considèrent comme dangereuse décident de l''envoyer en quarantaine sur une île au large de Manhattan. Commence alors pour Mary Mallon, femme indépendante, un combat à armes inégales pour sa liberté...','978-2264068170',6,8),
	('ONE PIECE Aventure au pays des samourais','Eiichiro Oda','Glénat Manga','2019-07-03','Français','Action, humour, aventures, magie, tous les ingrédients sont ici réunis pour une immense saga, passionnante et hilarante, qui ravit tous les publics. Depuis janvier 2011 One Piece est devenu le manga le plus vendu en France devant Naruto. Cette nouvelle édition propose une toute nouvelle traduction française fidèle à la version japonaise (noms originaux de tous les personnages, attaques, etc …) ainsi que des mêmes couvertures conformes à l''édition originale', '978-2344037102',7,9),
	('ONE-PUNCH MAN - tome 15','Yusuke MURATA','Kurokawa','2019-05-09','Français','Saitama est trop puissant ; tellement puissant qu''il élimine tous les monstres les plus farouches avec un simple coup de poing. Découvrez l''histoire du plus puissant des super-héros dans ce manga qui va vous mettre K.O. !!','978-2368527344',7,10),
	('Le solfège : Méthode simple et amusante en quatorze leçons','Daniel Ichbiah',' J''AI LU ','2013-08-31','Français','Passage obligé de tout musicien en herbe, le solfège n''est pas qu''une formalité rébarbative : c''est ce que prouve cet ouvrage. Loin des théories et des exercices fastidieux, cette méthode réinvente le solfège avec un joyeux mélange d''humour et de rigueur. De la simple lecture d''une partition à son interprétation virtuose en passant par l''étude des rythmes, ce petit guide vous initie pas à pas à la musique sans vous en dégoûter. Oubliez vos mauvais souvenirs, et prenez plaisir à apprendre! ','978-2290076606',8,11),
	('Burger quiz - Le cahier de jeux','Alain Chabat','Michel Lafon','2019-06-20','Français','" BURGER QUIZ " est un jeu télévisé inventé par Alain Chabat et Kader Aoun. Le concept de " Burger Quiz " consiste à répondre à des questions plus ou moins loufoques afin d''atteindre les 25 points, appelés Miams, avant l''équipe adverse. Les deux équipes, nommées Ketchup et Mayo, sont chacune composées de deux personnalités connues et d''un candidat anonyme. L''équipe vainqueur voit le candidat anonyme répondre à l''épreuve du " Burger de la mort ", où le présentateur pose dix questions les unes après les autres, après quoi le candidat doit y répondre correctement et dans l''ordre.','978-2749940526',9,12),
	('Les bonnes associations au potager','Noémie Vialard','RUSTICA','2007-02-16','Français','Les épinards sont plus tendres plantés près des fraisiers, mais l''oignon ne grossit pas à côté de la pomme de terre. L''aneth repousse la mouche de la carotte, et l''oeillet d''Inde, les nématodes... Les plantes s''aident mutuellement à prospérer. Leurs voisines peuvent modifier leur goût, influer sur leur croissance, chasser les nuisibles ou les piéger. Ce livre vous donne des conseils simples et précis de culture au potager et vous indique toutes les associations à privilégier ou à éviter, pour un potager en pleine santé. Au sommaire :La diversité au service du jardinier. Les mariages heureux : amour ou raison (31 légumes) : Ail * Artichaut * Asperge * Aubergine * Betterave * Carotte * Céleri branche * Céleri-rave * Chou-fleur * Chou cabus pommé * Chou de Bruxelles * Chou frisé * Concombre * Courge * échalote * épinard * Fenouil * Fève * Fraisier * Haricot * Maïs * Navet * Oignon * Poireau * Poirée * Pois * Poivron * Pomme de terre * Potiron * Radis * Tomate. Entre les légumes : les salades (5 plantes) : La chicorée frisée et la scarole * L''endive * La laitue * La mâche. Indispensables, les aromatiques et les fleurs (19 plantes aromatiques et 9 fleurs) : Le pouvoir des aromatiques * Les fleurs du potager. ','978-2840389743',9,13),
	('Le Réseau secret de la nature', 'Peter Wohlleben','Les Arènes','2019-04-03','Français','Saviez-vous que les arbres contribuent à la formation des nuages ? Que les loups peuvent modifier le cours des rivières ? Que le sort du sanglier dépend du ver de terre ? Dans la nature, tout est lié – comme les rouages d’une grande horloge. Aussi la moindre modification a-t-elle des répercussions insoupçonnées. Observateur scrupuleux et conteur passionné, Peter Wohlleben nous dévoile ces liens subtils qui unissent animaux et plantes, forêts et rivières, montagnes et climat…','978-2711200993',9,14),
	('Le livre des potions par Gastronogeek','Thibaud Villanova','Hachette Pratique','2015-09-16','Français','Le livre des potions est un ouvrage qui explore six univers classiques de la culture geek : la science-fiction, la fantasy, le fantastique, les comics, le manga et les jeux vidéo. Plus de 40 références cultes sont représentées à travers des recettes de cocktails, de smoothies, de jus, etc. : les Annales du Disque Monde, Peter Pan, le Cycle des Princes d Ambre, Star Trek, Stargate, Indiana Jones, Highlander... et bien sûr toutes les références qui nous ont déjà conquis dans Gastronogeek : Doctor Who, Harry Potter, Le Seigneur des Anneaux, Retour vers le futur... ','978-2011775894',10,15),
	('Le grand Larousse du vin','Collectif','Larousse','2018-08-22','Français',' Quand le vin devient une passion il vous invite au voyage, car il y a partout dans le monde des milliers de crus différents. Cependant, il est parfois difficile de s’y retrouver.Cet ouvrage vous aidera à mieux connaître les vins, mais aussi à devenir un amateur éclairé pour qui les termes de gouleyant, tuilé, charpenté, soyeux… n’auront plus de secret !','978-2035959676',10,16);



	
